import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Work@t - right place for the hard workers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Work@t</span>
        </h1>

        <p className={styles.description}>
          Get started by editing Registering your Passion
        </p>

        <div className={styles.grid}>
          <a href=" " className={styles.card}>
            <h2>Mechanic &rarr;</h2>
            <p>Find information about Vehicles need to be repaired.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Plumber &rarr;</h2>
            <p>Learn about the people who are in need of plumbing work .</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Carpenter &rarr;</h2>
            <p>Discover the people who need wood work to be done.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Labour &rarr;</h2>
            <p>
              Register and Get hired , in your local Area
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
